#!/usr/bin/env python3
"""Render the current-status section of ``docs/architecture/GAGOS_54_ORGANS.md``
from ``.aios/state/ORGAN_GREEN_LEDGER.json``.

Why this exists
---------------
The machine ledger is the only status authority, but the markdown that narrates
it was hand-written -- and on 2026-08-02 it fell eight organs behind. PRs #185,
#186 and #187 moved organs 20, 33, 35, 37, 40, 48, 49 and 51 to green in the
JSON and left the prose claiming 38 green / 16 yellow, with organs 33 and 35
still blamed on "no Ollama" after live Ollama evidence had landed. The document
passed CI the whole time, because ``release/organ-proof-manifest.json``
hash-pins it: that pin proves the file has not changed since someone last
blessed it, NOT that its contents match the ledger. A tamper-detector was being
read as a correctness guarantee.

This script closes that gap the same way ``build_release_manifest.py`` closed it
for the manifest: the status tables are generated, never written by hand.

What is generated, and what is not
----------------------------------
Only the region between the BEGIN/END markers is owned by this script. Every
dated narrative above it -- the Phase 1/2 tables, the re-audit sections, the
reconciliation notes -- is hand-written history and is preserved byte for byte.
That is deliberate: this document's append-only convention exists so dated
evidence is never silently rewritten, and a generator that reflowed the whole
file would destroy exactly the record the convention protects.

So the split is: **history is prose, current status is generated.**

Usage
-----
    python scripts/build_organ_ledger_doc.py            # rewrite the region
    python scripts/build_organ_ledger_doc.py --check    # CI: fail if stale

Ordering note: this script changes the markdown, and
``release/organ-proof-manifest.json`` hashes the markdown. Run this first, then
``build_release_manifest.py``, or the manifest check will fail on the very
change this script just made.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER_PATH = REPO_ROOT / ".aios" / "state" / "ORGAN_GREEN_LEDGER.json"
DOC_PATH = REPO_ROOT / "docs" / "architecture" / "GAGOS_54_ORGANS.md"

BEGIN_MARKER = "<!-- BEGIN GENERATED: CURRENT ORGAN STATUS -- do not hand-edit -->"
END_MARKER = "<!-- END GENERATED: CURRENT ORGAN STATUS -->"


def load_rows(path: Path = LEDGER_PATH) -> list[dict[str, Any]]:
    """Return the organ rows from the machine ledger, sorted by organ_id."""
    with path.open("r", encoding="utf-8") as fh:
        raw = json.load(fh)
    rows = raw if isinstance(raw, list) else raw.get("organs", [])
    return sorted(rows, key=lambda r: int(r["organ_id"]))


def ledger_sha256(path: Path = LEDGER_PATH) -> str:
    """Return the sha256 of the ledger file's exact bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _cell(text: Any) -> str:
    """Escape a value for use inside a markdown table cell."""
    if text is None:
        return "--"
    flat = " ".join(str(text).split())
    return flat.replace("|", "\\|") or "--"


def _residual(row: dict[str, Any]) -> str:
    blockers = row.get("known_blockers") or []
    if not blockers:
        return "--"
    return "<br>".join(_cell(b) for b in blockers)


def _proof(row: dict[str, Any]) -> str:
    evidence = row.get("live_evidence") or []
    levels = sorted({str(e.get("proof_level", "?")) for e in evidence})
    if not levels:
        return "none"
    return ", ".join(levels)


def render_block(rows: list[dict[str, Any]], *, ledger_digest: str) -> str:
    """Render the generated status region as markdown (LF newlines)."""
    green = [r for r in rows if r["status"] == "green"]
    other = [r for r in rows if r["status"] != "green"]

    lines: list[str] = [
        BEGIN_MARKER,
        "",
        "## Current organ status (generated)",
        "",
        "**This section is generated by `scripts/build_organ_ledger_doc.py` from",
        "`.aios/state/ORGAN_GREEN_LEDGER.json`. Do not hand-edit it.** Everything",
        "above it is dated, hand-written history and is preserved verbatim; only",
        "this region tracks current truth. If you moved an organ's status, run the",
        "script (then `build_release_manifest.py`) rather than editing here.",
        "",
        f"- **Counts:** {len(green)} green / {len(other)} yellow / {len(rows)} total",
        f"- **Source ledger sha256:** `{ledger_digest}`",
        "",
        "Status, owner, evidence SHA and residuals below are copied mechanically",
        "from the ledger. This section asserts only that it faithfully reflects",
        "the JSON -- not that the underlying evidence is sound. That judgement",
        "belongs to `scripts/verify_organ_contracts.py` and to the dated hands-on",
        "re-audits recorded above.",
        "",
        f"### Green ({len(green)})",
        "",
        "| # | Organ | Authority owner | Evidence SHA | Proof |",
        "|---|-------|------------------|--------------|-------|",
    ]

    for row in green:
        sha = row.get("last_verified_sha")
        sha_cell = f"`{str(sha)[:12]}`" if sha else "--"
        lines.append(
            f"| {row['organ_id']} | {_cell(row.get('name'))} "
            f"| `{_cell(row.get('authority_owner'))}` | {sha_cell} | {_proof(row)} |"
        )

    lines += [
        "",
        f"### Yellow ({len(other)}) — exact residual, from the ledger's own `known_blockers`",
        "",
        "| # | Organ | Authority owner | Residual |",
        "|---|-------|------------------|----------|",
    ]

    for row in other:
        lines.append(
            f"| {row['organ_id']} | {_cell(row.get('name'))} "
            f"| `{_cell(row.get('authority_owner'))}` | {_residual(row)} |"
        )

    lines += ["", END_MARKER]
    return "\n".join(lines)


def _dominant_newline(text: str) -> str:
    return (
        "\r\n" if text.count("\r\n") > text.count("\n") - text.count("\r\n") else "\n"
    )


def apply_block(doc_text: str, block: str) -> str:
    """Return *doc_text* with the generated region replaced (or appended)."""
    newline = _dominant_newline(doc_text)
    rendered = block.replace("\n", newline)

    start = doc_text.find(BEGIN_MARKER)
    end = doc_text.find(END_MARKER)
    if start != -1 and end != -1 and end > start:
        return doc_text[:start] + rendered + doc_text[end + len(END_MARKER) :]

    if start != -1 or end != -1:
        raise SystemExit(
            "GAGOS_54_ORGANS.md has only one of the generated-region markers; "
            "refusing to guess where the region begins or ends"
        )

    separator = newline + newline + "---" + newline + newline
    return doc_text.rstrip() + separator + rendered + newline


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the generated region is stale",
    )
    args = parser.parse_args(argv)

    rows = load_rows()
    block = render_block(rows, ledger_digest=ledger_sha256())

    with DOC_PATH.open("r", encoding="utf-8", newline="") as fh:
        current = fh.read()
    updated = apply_block(current, block)

    if args.check:
        if current != updated:
            print(
                f"{DOC_PATH.relative_to(REPO_ROOT).as_posix()}: generated organ-status "
                "region is stale relative to .aios/state/ORGAN_GREEN_LEDGER.json -- "
                "run `python scripts/build_organ_ledger_doc.py` (then "
                "`python scripts/build_release_manifest.py`)"
            )
            return 1
        print(f"{DOC_PATH.relative_to(REPO_ROOT).as_posix()} is up to date")
        return 0

    if current == updated:
        print(f"{DOC_PATH.relative_to(REPO_ROOT).as_posix()} already up to date")
        return 0

    with DOC_PATH.open("w", encoding="utf-8", newline="") as fh:
        fh.write(updated)
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
